---
title: "Regional Weather"
author: "Glenda Yenni"
date: "4/15/2020"
output: github_document
---
Patterns in precipitation, temperature, and ndvi


```{r global options, include = FALSE}
knitr::opts_chunk$set(echo=FALSE, include = TRUE, warning=FALSE, message=FALSE)
library(dplyr)
library(ggplot2)

```

```{r get data}

path = "~"

weather <- portalr::weather("daily")

portal4sw <- read.csv(portalr:::full_path('PortalData/Weather/Portal4sw_regional_weather.csv', path), na.strings = c(""), header = TRUE, stringsAsFactors = FALSE) %>%
   dplyr::select(c("year", "month", "day", "date", "name", "prcp", "snow", "tmax", "tmin", "tobs"))
 
sansimon <- read.csv(portalr:::full_path('PortalData/Weather/Sansimon_regional_weather.csv', path), na.strings = c(""), header = TRUE, stringsAsFactors = FALSE) %>%
    dplyr::select(c("year", "month", "day", "date", "name", "prcp", "snow"))

region <- dplyr::full_join(portal4sw, sansimon, by =
                               c("date", "year", "month", "day")) %>%
dplyr::arrange(.data$year,.data$ month, .data$day) %>%
dplyr::filter(.data$date >= "1980-01-01") %>%
    dplyr::mutate(date = as.Date(date))

full_weather <- weather %>%
    dplyr::full_join(region, by = c("date", "year", "month", "day"))

```

## Local vs regional weather stations

### Precipitation

Looking at zeros separately, since they are most values

```{r precipitation}

theme_set(theme_minimal())
ggplot(data = full_weather[full_weather$precipitation != 0,], aes(x = precipitation)) + 
  geom_point(aes(y = prcp.x, color = "SW_Portal")) +
  geom_point(aes(y = prcp.y, color = "San_Simon")) +
    geom_abline() +
  scale_color_manual(name="",
                     values = c("SW_Portal"="lightblue","San_Simon"="pink")) +
  labs(x = 'Portal ppt', y = 'regional ppt') +
  theme(legend.position = "top") 

sw <- full_weather %>%
    filter(!is.na(name.x)) %>%
    mutate(name = "SW_Portal") %>%
    rename(prcp = prcp.x) %>%
    select("date", "name", "precipitation", "prcp")

sansimon <- full_weather %>%
    filter(!is.na(name.y)) %>%
    mutate(name = "San_Simon") %>%
    rename(prcp = prcp.y) %>%
    select("date", "name", "precipitation", "prcp")

zeros <- rbind(sw, sansimon) %>%
    filter(precipitation == 0)

theme_set(theme_minimal())
ggplot(data = zeros, 
       aes(x = name, y = prcp, color = name)) + 
  geom_dotplot(binaxis='y', stackdir='up', binwidth = 1, stackratio = .5) +
    xlab("Station") + ylab("precipitation (mm)") + 
    labs(title = "Portal 0 precip", subtitle = "What is regional ppt when there is 0 ppt at the site?")

```

### Minimum Temperature

We only have temperatures from SW_Portal

```{r mintemp}

theme_set(theme_minimal())
ggplot(data = full_weather, aes(x = mintemp)) + 
  geom_point(aes(y = tmin, color = "SW_Portal")) +
  geom_abline() +
  scale_color_manual(name="",
                     values = c("SW_Portal"="blue")) +
  labs(x = 'Portal C', y = 'regional C') +
  theme(legend.position = "top") 

```

### Maximum Temperature

We only have temperatures from SW_Portal

```{r maxtemp}

theme_set(theme_minimal())
ggplot(data = full_weather, aes(x = maxtemp)) + 
  geom_point(aes(y = tmax, color = "SW_Portal")) +
  geom_abline() +
  scale_color_manual(name="",
                     values = c("SW_Portal"="red")) +
  labs(x = 'Portal C', y = 'regional C') +
  theme(legend.position = "top") 

```
